#!/bin/bash
# Generated by ChatGPT

awk -v FS='\t' -v OFS='\t' '
{
    cluster = $7
    cmd = "grep -l \"" cluster "\" ../../HAP*/workingdir_chr1/*calls.txt"
    cmd | getline filepath
    close(cmd)

    n = split(filepath, a, "/")
    dirname = a[n-2]   # grabs HAPMAPMIX.uwsc.minimap2_GRCh38.aligned.sorted.bam_workingdir

    print $0, dirname
}
' input.txt > output_with_directory.txt

