#!/bin/bash
# Generated by ChatGPT

echo "Checking for missing PALMER output files..."
echo

# Find all workingdir_chr folders under any *workingdir* directory
find . -type d -name "workingdir_chr*" | while read dir; do
    chr=$(basename "$dir" | sed 's/workingdir_chr//')

    calls_file="$dir/Output_chr${chr}_numts_calls.txt"
    tsd_file="$dir/Output_chr${chr}_numts_TSD_reads.txt"

    missing=0
    if [[ ! -f "$calls_file" ]]; then
        echo "❌ Missing calls file: $calls_file"
        missing=1
    fi

    if [[ ! -f "$tsd_file" ]]; then
        echo "❌ Missing TSD file:   $tsd_file"
        missing=1
    fi

    if [[ $missing -eq 0 ]]; then
        echo "✅ All files present for chr${chr} in: $dir"
    fi

    echo
done
